name: 'validate-dependabot'
description: 'validate dependabot yaml'
author: 'marocchino'
inputs:
  path: # change this
    required: true
    description: 'path of dependabot yaml file'
    default: '.github/dependabot.yml'
runs:
  using: 'node12'
  main: 'dist/index.js'
